const express = require('express')
const app = express()
const morgan = require('morgan')
var cors = require('cors')
require('dotenv').config()
const methodOverride = require('method-override')
const shortid = require('shortid')
var multer = require('multer')
const path = require('path')
const util = require('util')
const fs = require('fs')
const cookieParser = require('cookie-parser')
const client = require('./config/connect')
const db = require('./config/connectdb')
const route = require('./routes')
db.connect()
app.use(express.static(__dirname));
app.use(express.urlencoded({ extended: true }))
app.use(express.json())
app.use(cors())
app.use(cookieParser())
app.use(morgan('combined'))
app.use(methodOverride('_method'))
app.use(cors())
route(app)
app.listen(3000, () => {
    console.log('App listening on port 3000!')
})
